/**
 ******************************************************************************
 * @file           : pressure_sensor.h
 * @brief          : Pressure sensor data structure and depth calculation
 * @author         : Generated by Claude Code
 * @date           : 2026-02-11
 ******************************************************************************
 * @attention
 *
 * Depth monitoring subsystem for MS5849 pressure sensor integration.
 * This module provides data structures and functions for pressure-based
 * depth calculation following the existing O2 sensor architecture patterns.
 *
 * Assumptions:
 * - External process (future I2C driver) updates pressure_mbar and temperature_c
 * - No temperature compensation in this phase
 * - Fixed atmospheric pressure reference (1013.25 mbar)
 * - Integer arithmetic only (no floating point)
 *
 ******************************************************************************
 */

#ifndef PRESSURE_SENSOR_H
#define PRESSURE_SENSOR_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>
#include <stdbool.h>

/* Exported types ------------------------------------------------------------*/

/**
 * @brief Pressure sensor data structure
 *
 * Memory footprint: 21 bytes
 * - pressure_mbar: 4 bytes
 * - temperature_c: 2 bytes
 * - depth_mm: 4 bytes
 * - surface_pressure_mbar: 4 bytes
 * - pressure_valid: 1 byte
 * - padding: 6 bytes (compiler alignment)
 * Total: 21 bytes (actual: 24 bytes with padding)
 */
typedef struct {
    int32_t pressure_mbar;          /*!< Current pressure in millibars × 100 (101325 = 1013.25 mbar) */
    int16_t temperature_c;          /*!< Temperature in degrees Celsius × 100 (3000 = 30.00°C) */
    int32_t depth_mm;               /*!< Calculated depth in millimeters (signed: negative = above sea level) */
    int32_t surface_pressure_mbar;  /*!< Reference surface pressure for depth calculation (× 100) */
    bool pressure_valid;            /*!< Data validity flag (true = valid sensor data) */
} pressure_sensor_data_t;

/* Exported constants --------------------------------------------------------*/

/**
 * @brief Standard atmospheric pressure at sea level
 *
 * Value: 1013.25 mbar × 100 = 101325 (scaled for integer arithmetic)
 */
#define ATMOSPHERIC_PRESSURE_MBAR   101325

/**
 * @brief Standard temperature for initialization
 *
 * Value: 30.00°C × 100 = 3000 (scaled for integer arithmetic)
 */
#define STANDARD_TEMPERATURE_C      3000

/* Exported functions --------------------------------------------------------*/

/**
 * @brief Initialize pressure sensor data structure
 *
 * Sets initial values:
 * - surface_pressure_mbar = 101325 (1013.25 mbar)
 * - pressure_mbar = 101325 (atmospheric pressure)
 * - temperature_c = 3000 (30.00°C)
 * - depth_mm = 0 (at surface)
 * - pressure_valid = true
 *
 * @note Call once during system startup after sensor_init()
 * @note External process (I2C driver) will update pressure_mbar later
 */
void pressure_sensor_init(void);

/**
 * @brief Calculate depth from pressure difference
 *
 * Uses seawater depth formula: depth = (P_current - P_surface) / (ρ × g)
 *
 * Parameters:
 * - ρ (seawater density) = 1025 kg/m³
 * - g (gravity) = 9.80665 m/s²
 * - Conversion: 1 mbar = 100 Pa
 *
 * Formula: depth_mm = ((P_current - P_surface) × 995) / 100
 *
 * @param current_pressure_mbar Current pressure reading (scaled × 100)
 * @param surface_pressure_mbar Surface reference pressure (scaled × 100)
 * @return Depth in millimeters (signed: positive = below surface, negative = above)
 *
 * @note Result range: ±2,147,483,647 mm (±2,147 km, far exceeds diving depths)
 * @note Max realistic depth: 330 m (33 bar) = 330,000 mm (well within int32_t)
 *
 * @example
 * // At surface: 1013.25 mbar
 * depth = pressure_sensor_calculate_depth_mm(101325, 101325);
 * // Result: 0 mm
 *
 * // At 10m depth: 2013.25 mbar (additional 1000 mbar pressure)
 * depth = pressure_sensor_calculate_depth_mm(201325, 101325);
 * // Result: ~9950 mm ≈ 10.0 m
 */
int32_t pressure_sensor_calculate_depth_mm(int32_t current_pressure_mbar, int32_t surface_pressure_mbar);

#ifdef __cplusplus
}
#endif

#endif /* PRESSURE_SENSOR_H */
